### ISSUE TITLE
Kieran general issue with logs

### ISSUE THREAD

**Issue by aljosephson** [AIDELabAZ/weather_and_agriculture#12]
Kieran having trouble with log files. @KieranCDouglas  - could you add a note here which describes the error you see?

**Comment by KieranCDouglas** [comment]
Basically I try to run this:
cap log 		close
	log using 		"$logout/2019_agsec3a", append
and receive this error message:
(file /2019_agsec3a.smcl not found)
file /2019_agsec3a.smcl could not be opened
r(603);

The 2019_agsec3a.smcl file is in my local onedrive folder but when I look at the online folder I do not see it.

**Comment by KieranCDouglas** [comment]
Resolved!
