### ISSUE TITLE
total value of production - all crops (local currency)

### ISSUE THREAD

**Issue by rguerrasu** [AIDELabAZ/weather_and_agriculture#15]
In Uganda we generate crop value in two ways, one imputing value based on sold amount and the other calculating local prices and imputing values based on prices times quantity. The first one is what we used in Uganda while the other method is used in other countries. The first method results in lower crop values. Based on summary stats in the populated PAP Uganda has much lower yields and much lower crop value than other countries. Once all waves are completed we should reassess the decision about which value imputation method to use.

**Comment by jdavidm** [comment]
Took us a while but we realized there was a switch in seasons. Uganda is now complete except wave 7, which may never be complete because of missing land area in wave 7.
