### ISSUE TITLE
Almost 2/3 of the values in sold data are 0 in 2019_agsec5a 

### ISSUE THREAD

**Issue by KieranCDouglas** [AIDELabAZ/weather_and_agriculture#20]
**Describe the bug**
Line 305 under section 4 (generating sold harvest values) attemps to replace zeros in sold data as missing. When you run it, ~2/3 of the values are then converted to missing (3932). 

**To Reproduce**
1. Go to line 304 in 2019_agsec5a
2. Run line:  replace			s5aq07a_1 = . if s5aq07a_1 == 0
3. Converts 3932 to missing

**Screenshots**
<img width="528" alt="Screenshot 2024-05-10 at 11 35 03 AM" src="https://github.com/AIDELabAZ/weather_and_agriculture/assets/143770423/af2e22fd-38bd-4246-aa6d-779d1028fb4e">

**Comment by jdavidm** [comment]
I worked through and cleaned all of this wave and sorted this issue. Don't recall how.
